name: MongoDB Atlas CLI Setup and Verification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-mongo-atlas-cli:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install MongoDB Atlas CLI
    - name: Install MongoDB Shell (mongosh)
      run: |
        wget -q https://downloads.mongodb.com/compass/mongosh-1.10.0-linux-x64.tgz
        tar -xzf mongosh-1.10.0-linux-x64.tgz
        mv mongosh-1.10.0-linux-x64/bin/mongosh /usr/local/bin/

    # Step 3: Export MongoDB URI
    - name: Export MongoDB URI
      run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> $GITHUB_ENV

    # Step 4: Create Collection
    - name: Create Collection and Schema
      run: |
        mongosh "${{ secrets.MONGO_CONNECTION_URI }}" <<EOF
        db
        db.myCollection.insertOne({ name: "example", value: 123 })
        EOF
