name: MongoDB Atlas CLI Setup and Verification

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-mongo-atlas-cli:
    runs-on: ubuntu-22.04

    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Install MongoDB Atlas CLI
    - name: Install MongoDB Atlas CLI
      run: |
        curl -fsSL https://pgp.mongodb.com/server-6.0.asc | sudo gpg --dearmor -o /usr/share/keyrings/mongodb-server-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/mongodb-server-keyring.gpg] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
        sudo apt-get update
        sudo apt-get install -y mongodb-atlas-cli

        
    # Step 3: Configure MongoDB Atlas CLI
    - name: Configure MongoDB Atlas CLI
      env:
        MONGODB_ATLAS_PUBLIC_API_KEY: ${{ secrets.MONGO_ATLAS_PUBLIC_KEY }}
        MONGODB_ATLAS_PRIVATE_API_KEY: ${{ secrets.MONGO_ATLAS_PRIVATE_KEY }}
        MONGODB_ATLAS_ORG_ID: ${{ secrets.MONGO_ATLAS_ORG_ID }} # Optional, organization ID
        MONGODB_ATLAS_PROJECT_ID: ${{ secrets.MONGO_ATLAS_PROJECT_ID }} # Optional, project ID
      run: |
        atlas config init --profile default

    # Step 4: Verify MongoDB Atlas CLI Configuration
    - name: Verify MongoDB Atlas CLI Configuration
      run: |
        echo "Listing MongoDB Atlas projects..."
        mongocli projects list --output json
